### ISSUE TITLE
Perf averaged over multiple experimental runs

### ISSUE THREAD

**Issue by YoungXIAO13** [jiaxi-wu/MPSR#10]
Hi,

Thx for sharing the code. I have just one question about the evaluation protocol of few-shot object detection.

As proposed in the recent paper [TFA](https://github.com/ucbdrive/few-shot-object-detection), where the performances are computed as an average of multiple experimental runs with random support images, have you also done this in your work and report the averaged results somewhere ?

**Comment by jiaxi-wu** [comment]
Hi, @YoungXIAO13 
We just evaluate our method on datasplits provided by [FSRW](https://github.com/bingykang/Fewshot_Detection) (also in TFA's section 4.1) and our natural sampling strategy (you can find them at `tools/fewshot_exp/datasets/voc_sample_series.py`). 

The **Generalized few-shot object detection benchmark** is a new contribution of TFA which shows the large sample variance that we ignored before. However, their paper was available at arxiv after our paper submission. So we did not add this evaluation into our work.

If you are curious about how well our method works on this generalized benchamrk, please evaluate it by yourself since we don't have resources for this temporarily. Thanks & looking forward to your reply.

**Comment by YoungXIAO13** [comment]
Thanks for your reply.
Another question I'm wondering is that do you exclude all the training samples containing novel classes in the base training stage, or do you treat novel objects as background as mentioned [here](https://github.com/ucbdrive/few-shot-object-detection/issues/5#issuecomment-603669111) ?

**Comment by jiaxi-wu** [comment]
I exclude images containing novel samples in the base training stage (`tools/fewshot_exp/datasets/voc_create_base.py`).
